use_frameworks!

target 'Swiftlytics_Example' do
  pod 'Swiftlytics', :path => '../'
  pod 'Swiftlytics/Firebase', :path => '../'
  pod 'Swiftlytics/AppsFlyer', :path => '../'
  pod 'Swiftlytics/Facebook', :path => '../'

  target 'Swiftlytics_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
